import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {googleBasicApplication,googleProgram} from '../backend/storage-policy.mjs';
const application={id:'test-id',applicant_name:'가상신청자',birth_date:'2000-01-01',phone:'01000000000',created_at:'2026-09-09',signature:'PRIVATE_SIGNATURE',consent_responses:{a:'agree'},note:'PRIVATE_NOTE',base_consent_snapshot:[{text:'PRIVATE_CONSENT'}]};
const payload=JSON.stringify({application:googleBasicApplication(application),program:googleProgram({id:'p',title:'프로그램',consent_items:[{text:'PRIVATE_CONSENT'}]})});assert(!payload.includes('PRIVATE_'));assert(payload.includes('가상신청자'));
const code=fs.readFileSync(new URL('../backend/google-apps-script.gs',import.meta.url),'utf8');let html='',files=[],folders=[];
function folder(name){const entries=new Map();return {getUrl:()=>name,getId:()=>name,getFilesByName:n=>({hasNext:()=>entries.has(n),next:()=>entries.get(n)}),createFile:blob=>{let text=blob.text;const file={getUrl:()=>name+'/'+blob.name,getId:()=>blob.name,getBlob:()=>({getDataAsString:()=>text}),setContent:t=>text=t};files.push({blob,file});entries.set(blob.name,file);return file;}};}
const programFolder=folder('program'),uploadFolder=folder('uploads');
const ctx={DriveApp:{getFolderById:()=>folder('root')},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'test-secret'})},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Session:{getScriptTimeZone:()=> 'Asia/Seoul'},Utilities:{formatDate:()=> '2026-09-09',base64Decode:()=>[1,2],parseCsv:text=>text.split(/\r?\n/).filter(Boolean).map(l=>l.slice(1,-1).split('","')),newBlob:(text,mime,name)=>({text,mime,name})},ContentService:{MimeType:{JSON:'json'},createTextOutput:text=>({setMimeType:()=>JSON.parse(text)})},HtmlService:{createHtmlOutput:text=>{html=text;return {getAs:()=>({setName:name=>({text,mime:'application/pdf',name})})}}},MimeType:{PDF:'application/pdf'}};
vm.runInNewContext(code,ctx);ctx.getOrCreateFolder_=(_parent,name)=>{folders.push(name);return name==='신청서 모음'?uploadFolder:programFolder;};
let result=ctx.doPost({postData:{contents:JSON.stringify({secret:'test-secret',application,program:{id:'p',title:'프로그램'},targetFolderId:'123456789012345'})}});assert(result.ok,result.error);assert.deepEqual(folders,['프로그램']);assert(files.every(x=>x.blob.mime.startsWith('text/csv')));assert(!files[0].blob.text.includes('PRIVATE_'));assert(!files[0].blob.text.includes('전자서명'));assert(!files[0].blob.text.includes('동의 -'));
result=ctx.doPost({postData:{contents:JSON.stringify({secret:'test-secret',application,program:{id:'p',title:'프로그램'},targetFolderId:'123456789012345',file:{name:'첨부.pdf',mimeType:'application/pdf',base64:'eA=='}})}});assert(result.ok,result.error);assert(result.uploadedFileUrl.includes('test-id'));assert(folders.includes('신청서 모음'));
ctx.nurimPdf_(folder('survey'),'survey.pdf',{title:'설문',description:'',questions:[{id:'q',label:'설문 내 동의',type:'consent',help:'설문 자체 문항은 유지',options:[],required:true}]},{name:'가상신청자',birth:'2000-01-01',phone:'01000000000',answers:{q:'agree'},extra:{signature:'PRIVATE_SIGNATURE',consentItems:[{text:'PRIVATE_CONSENT'}]}});assert(html.includes('설문 내 동의'));assert(html.includes('동의'));assert(!html.includes('PRIVATE_'));assert(!html.includes('기본 신청 및 개인정보 동의'));
console.log('Google payload excludes base consent; basic CSV only; upload adds file; survey PDF keeps survey questions but excludes base consent.');

