import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const code=fs.readFileSync(new URL('../backend/google-apps-script.gs',import.meta.url),'utf8');
const iter=a=>{let i=0;return {hasNext:()=>i<a.length,next:()=>a[i++]}};
let seq=0;const registry=new Map();
class Folder{constructor(name,parent){this.name=name;this.parent=parent;this.children=[];this.files=[];this.desc='';}getName(){return this.name}setName(n){this.name=n;return this}getDescription(){return this.desc}setDescription(s){this.desc=s;return this}getUrl(){return this.name}getFolders(){return iter(this.children)}getFoldersByName(n){return iter(this.children.filter(f=>f.name===n))}createFolder(n){let f=new Folder(n,this);this.children.push(f);return f}moveTo(p){if(this.parent)this.parent.children=this.parent.children.filter(f=>f!==this);this.parent=p;p.children.push(this);return this}getFiles(){return iter(this.files)}getFilesByName(n){return iter(this.files.filter(f=>f.name===n))}createFile(n,data){let f={name:n,data,getName(){return this.name},getUrl(){return this.name},setContent(v){this.data=v},getBlob(){return {getDataAsString:()=>this.data}}};this.files.push(f);return f}}
class Tab{constructor(n){this.n=n;this.rows=[]}getName(){return this.n}setName(n){this.n=n;return this}getLastRow(){return this.rows.length}getMaxRows(){return 1000}getRange(r,c,n=1,m=1){const self=this;return {setValue(v){return this.setValues([[v]])},setValues(v){v.forEach((row,i)=>{self.rows[r-1+i]??=[];row.forEach((x,j)=>self.rows[r-1+i][c-1+j]=x)});return this},getValue(){return self.rows[r-1]?.[c-1]},getValues(){return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>self.rows[r-1+i]?.[c-1+j]??''))},getDisplayValues(){return this.getValues().map(row=>row.map(String))},setNumberFormat(){return this}}}}
function makeBook(n){const id=String(++seq);const b={id,tabs:[new Tab('Sheet1')],getId(){return id},getUrl(){return id},getSheets(){return this.tabs},getSheetByName(n){return this.tabs.find(t=>t.n===n)},insertSheet(n){let t=new Tab(n);this.tabs.push(t);return t}};registry.set(id,b);b.file={name:n,getName(){return this.name},getId:()=>id,moveTo(p){p.files.push(this)}};return b}
const root=new Folder('기관');const ctx={PropertiesService:{getScriptProperties:()=>({getProperty:()=>""})},DriveApp:{getFolderById:()=>root,getFileById:id=>registry.get(id).file},SpreadsheetApp:{create:makeBook,openById:id=>registry.get(id),flush(){}},MimeType:{CSV:'csv'},};vm.runInNewContext(code,ctx);
ctx.nurimHeaders_=t=>{if(!t.rows.length)t.rows.push(Array(10).fill('header'))};ctx.nurimPdf_=(f,n)=>({getUrl:()=>f.getUrl()+'/'+n});
const sid='6b3561b2-e14f-4737-aba7-bd943809eac1';const old=root.createFolder('설문_'+sid);const template=makeBook('설문응답');template.file.moveTo(old);ctx.nurimHeaders_(template.insertSheet('v3'));
const schema={questions:[]};old.createFolder("이전버전").createFile("문항_v3.json",JSON.stringify(schema));function submit(pid,id){return ctx.nurimSurveyRoute_({action:'nurim-survey-submit',targetFolderId:'123456789012',surveyId:sid,revision:3,schema,program:{id:pid,title:'프로그램 '+pid},record:{id,name:'가상',created_at:id,program_id:pid,program_title:'프로그램 '+pid,birth:'2000-01-01',phone:'01000000000',answers:{}}})}
submit('A','a');submit('B','b');submit('A','a');
assert.equal(root.getFoldersByName('설문_'+sid).hasNext(),false);assert.equal(template.getSheetByName('v3').getLastRow(),1);
const a=ctx.nurimProgramFolderById_(root,'A'),b=ctx.nurimProgramFolderById_(root,'B');assert.notEqual(a,b);
const ab=ctx.nurimResponseBook_(a,sid,false),bb=ctx.nurimResponseBook_(b,sid,false);assert.equal(ab.getSheetByName('v3').getLastRow(),2);assert.equal(bb.getSheetByName('v3').getLastRow(),2);
assert(a.files.find(f=>f.name==='전체신청명단.csv').data.includes('"a"'));assert(!a.files.find(f=>f.name==='전체신청명단.csv').data.includes('"b"'));assert(!old.files.some(f=>f.name==='전체신청명단.csv'));
const result=ctx.nurimSurveyRoute_({action:'nurim-survey-responses',targetFolderId:'123456789012',surveyId:sid,revision:3});assert.equal(result.total,2);
ctx.nurimSurveyRoute_({action:'nurim-survey-sync-basic',targetFolderId:'123456789012',surveyId:sid,revision:3,application:{id:'a',program_id:'A',applicant_name:'수정',phone:'01000000000',birth_date:'2000-01-01',last_action_at:'2026-09-09',application_status:'confirmed'}});

assert.equal(ab.getSheetByName('v3').rows[1][3],'수정');assert.equal(bb.getSheetByName('v3').rows[1][3],'가상');console.log('PASS: program isolation, CSV, retry, aggregate lookup and update');

